vertex_num: 10

# define the prism circumcised radius, (cm)

circumcised_radius: 20

# define the rotation angle of the prism (degree)
rotation_angle: 0

camera_relative_percentage: -0.75
camera_relative_position_y_shift: 11.7
camera_degree : -9
camera_position_x : -20

# prism position, (cm)
prism_position : [0, 49.14]

plane_y : 0

# Set the x-axis and y-axis view limits.(cm)
x_lim : [-100, 100]
y_lim : [-100, 100]
