# => Chessboard square size in mm
square_size: 20.

# => Chessboard thickness in mm
thickness: 5.

# => Corner number in the x (width) direction
corner_columns: 11

# => Corner number in the y (height) direction
corner_rows: 8

# => Functional pattern area width, square_size * (corner_columns - 1), in mm
pattern_width: 200.

# => Functional pattern area height, square_size * (corner_rows - 1), in mm
pattern_height: 140.
