sam_model_path: C:\Users\SUN Zheng\OneDrive - The Chinese University of Hong Kong\CUHK学习\研究工作\高光谱相机项目\论文相关\icra\model\sam_vit_b_01ec64.pth
spectral_model_type: "boulch"
spectral_model_path: C:\Users\SUN Zheng\OneDrive - The Chinese University of Hong Kong\CUHK学习\研究工作\高光谱相机项目\论文相关\icra\model\boulch.pth


server_ip: '127.0.0.1'
spectral_data_port: 8080
switch_signal_port: 8081

robot_ip: '127.0.0.10'
robot_control_port: 9090

motor_rpm: 16

rgb_region_bbox: [168, 193, 1160, 1000]


# calculate_detection_line_position(-45)
motor_limited_position_left: -200.864

# calculate_detection_line_position(-9)
motor_limited_position_right: 304.809

experimental_signal_transmission_time: 0.09 #s

channels: 350

cnn_shape: 1

class_dict:
  0: "background"
  1: "white_polyester"
  2: "white_linen"
  3: "white_silk"
  4: "white_wool"
  5: "white_cotton"
  6: "white_0.5poly+0.5vis"
  7: "white_lyocell"
  8: "white_acetate"
  9: "white_0.1ac+0.9vis"
  10: "black_polyester"
  11: "black_linen"
  12: "black_silk"
  13: "black_wool"
  14: "black_cotton"
  15: "black_0.5poly+0.5vis"
  16: "black_lyocell"
  17: "black_acetate"

reference_dir: C:\Users\SUN Zheng\OneDrive - The Chinese University of Hong Kong\CUHK学习\研究工作\高光谱相机项目\论文相关\光谱数据\衣物